### PR TITLE
Task 05.8 Refactoring : Semester Model

### PR DESCRIPTION
**Pull request by JaleneA**
1. Include str and repr
2. Included academicYear here instead, to be removed from courseOffering Model in other branch
3. Adjusted get_json and init to suit

### CODE REVIEW

**Review by RynniaRyan — COMMENTED** [review]
**Fixes**
1. Confine attributes to newly updated Model diagram
   a. academicYear
   b. Change semesterName to semesterTitle

**Comment by JaleneA** [comment]
@RynniaRyan This Model Diagram would need to be updated to suit this, the code went outside the current Model Diagram for better implementation

**Review by RynniaRyan — CHANGES_REQUESTED** [review]
We will update the model diagram to reflect this change. The addition of the 'academicYear' attribute is necessary for differentiating semesters

Add **str** function. Here is one for free:
```
def __str__(self):
    return (f"Semester(semesterName={self.semesterName}, "
            f"academicYear={self.academicYear}, "
            f"startDate={self.startDate}, "
            f"endDate={self.endDate})")
```

**Comment by JaleneA** [comment]
@RynniaRyan The code already have an str function (Its also listed in my initial commit of stuff I included)

**Comment by RynniaRyan** [comment]
> @RynniaRyan  The code already have an str function (Its also listed in my initial commit of stuff I included)

@JaleneA  Oh goodness, my aplogiesssssss 🙇‍♀️

**Review by RynniaRyan — APPROVED** [review]
**Str** slipped my eye there.  Thank you for your correction, lookin good. Approved 👍

**Pull request merged**
