### PR TITLE
09.1.Post-CLI and Post-Tests Cleanup

### PR DESCRIPTION
**Pull request by JaleneA**
Details on what we mended and included is outlined in the "09.1. Post-CLI and Post-Tests Cleanup" Card on the Trello Board

### CODE REVIEW

**Comment by JaleneA** [comment]
[09.1. Post-CLI and Post-Tests Cleanup](https://trello.com/c/NA7A4s3c/117-091-post-cli-and-post-tests-cleanup)

**Review by stu-dent101 — COMMENTED** [review]
the unit and integration test are passing

and

I wanted to test the add_course command since I saw it highlighted green on GitHub

I initialized the database, created a staff object
I tried to add the staff to a course but it was missing the attribute 'courseCode'
I created a course object
I tried to add the staff to the course but it was missing the attribute 'semesterID'
I created a semester object, then it told me "{'Error': 'Course Offering Not Found For The Given Semester'}"
I tried looking for a command that would add a course to a semester but I did notice any, you'll let me know if it's there but I missed it.

**Comment by JaleneA** [comment]
@stu-dent101 Yeah a command to add a course to a semester it missing lol
There's so many commands you then to get lost

**Comment by JaleneA** [comment]
I'll make another task and branch to add and do all the changes to the updated CLI commands, since this branch was used to make 07.3. Special Feature CLI Commands Implementation, its changes are already approved, I'll close this pull request.

And I'll merge the pull request for that approved task and make a new branch from there to do a task to all the final changes and additions to CLI, within the task card I'll make a checklist.

@stu-dent101 @RynniaRyan @DaNJO-Y

**Pull request closed without merging**
