### PR TITLE
Task 06.3 Refactoring : User Controller

### PR DESCRIPTION
**Pull request by JaleneA**
Refactored Controllers
validate_Staff()
validate_Admin()
get_user()
get_userID()

Added Controllers
create_user()
get_all_admin_users()
get_all_staff_users()
get_all_admin_users_json()
get_all_staff_users_json()

### CODE REVIEW

**Review by RynniaRyan — COMMENTED** [review]
**Question: Why Addition of validate_Staff & validate_Admin?**
I thought all authentication is to be done within [auth.py](https://github.com/Fairly-Odd-Functions/Assessment-Scheduler-FOF/blob/main/App/controllers/auth.py)?

_Any explanations as to why this decision was made?_
@JaleneA

**Comment by JaleneA** [comment]
@RynniaRyan I didn't add those two, as stated in my commit message I simply refactored it, the original project had it already and I just left it, we don't need to use it if we don't need to but its there and acts as a helper function for the others

**Comment by RynniaRyan** [comment]
> @RynniaRyan I didn't add those two, as stated in my commit message I simply refactored it, the original project had it already and I just left it, we don't need to use it if we don't need to but its there and acts as a helper function for the others

**Proposal: Refactoring of get_user()**
Ah I see, the use of  helper function. Well can you refactor get_user and make this change to reduce redundancy:

```
def get_user(email, password):
    # Check if the user is a staff
    user = validate_Staff(email, password)
    if user:
        return user  # User is a Staff
    
    # Check if the user is an admin
    user = validate_Admin(email, password)
    if user:
        return user  # User is an Admin
    
    # If neither, return None
    return None
```
@JaleneA

**Comment by JaleneA** [comment]
@RynniaRyan No, there is no redundancy hre

> > @RynniaRyan I didn't add those two, as stated in my commit message I simply refactored it, the original project had it already and I just left it, we don't need to use it if we don't need to but its there and acts as a helper function for the others
> 
> **Proposal: Refactoring of get_user()** Ah I see, the use of helper function. Well can you refactor get_user and make this change to reduce redundancy:
> 
> ```
> def get_user(email, password):
>     # Check if the user is a staff
>     user = validate_Staff(email, password)
>     if user:
>         return user  # User is a Staff
>     
>     # Check if the user is an admin
>     user = validate_Admin(email, password)
>     if user:
>         return user  # User is an Admin
>     
>     # If neither, return None
>     return None
> ```
> 
> @JaleneA

@RynniaRyan There is no redundancy here, the code reads to first see if the email provided is that of a Staff and return, if not it'll check if it belongs to an Admin and return, if not it'll return none.

**Review by RynniaRyan — APPROVED** [review]
> @RynniaRyan There is no redundancy here, the code reads to first see if the email provided is that of a Staff and return, if not it'll check if it belongs to an Admin and return, if not it'll return none.

Alrighty then, I have no other concerns. Approved 👍

**Pull request merged**
