### PR TITLE
08.Unit & Integration Tests Implementation

### PR DESCRIPTION
**Pull request by JaleneA**
_This is the grand branch that contains both Unit and Integration Tests_

**Status** 
- Two (2) commented out Test needs complex external changes to other files
- Twenty (20) **_Passing_** Tests

- Unit Test Implementation {Broken-Up into 3 Tasks]- @stu-dent101 
- Integration Test Implementation [Broken-Up into 5 Tasks]  - @DaNJO-Y 
- Conflict Resolver, Code Organization & Fixes - @JaleneA

### CODE REVIEW

**Comment by JaleneA** [comment]
[08.3. Unit & Integration Tests Fixes](https://trello.com/c/hbxKS9xt/120-083-unit-integration-tests-fixes)

**Review by RynniaRyan — COMMENTED** [review]
**Question: Where are the Unit Test For other Independent Models?**

I know that the assigned tasks only included for Admin, Staff  and User but. . .How come there isn't any Unit Test for the other independent models where this can be applied? Such as:
      1. Course
      2. Semester
      3. Programme
      4. Assessment
    
@stu-dent101

**Comment by stu-dent101** [comment]
I'll get to it now

**Review by RynniaRyan — APPROVED** [review]
Great work guyssss! 🥹. Mega Approved 👍

**Pull request merged**
