### PR TITLE
Task 05.9 Refactoring : Assessment Model

### PR DESCRIPTION
**Pull request by RynniaRyan**
Clean up on assesment.py included:
- Remove category attribute
- Add str()function
- Add repr() function

### CODE REVIEW

**Comment by JaleneA** [comment]
1. Remove startDate and dueDate attributes
2. Remove assessmentID from __init__ (as well as startDate and dueDate)
3. Everything else is good just update the other functions to suit (i.e. repr, get_json, str)
4. Remove unused enum import

Optional: Clean up the code a bit, spacing out, labelling the attributes with #Attributes, remove excess whitespaces 👍🏽✨

**Review by JaleneA — CHANGES_REQUESTED** [review]
1. Remove enum import
2. Remove courseCode attribute (courseAssessment takes care of this)
3. Refactor get_json, str and repr to suit

**Comment by RynniaRyan** [comment]
> 1. Remove enum import
> 2. Remove courseCode attribute (courseAssessment takes care of this)
> 3. Refactor get_json, str and repr to suit

@JaleneA Just did 👍

**Review by JaleneA — APPROVED** [review]
Awesome, Approved 👍🏽✨

**Pull request merged**
