### PR TITLE
Task 06.2 Refactoring : Staff Controller

### PR DESCRIPTION
**Pull request by JaleneA**
Refactored Existing Controllers
register_staff
add_course_staff
get_staff_courses (was get_registered_courses)

Added New Controllers
add_multiple_courses_to_staff
update_staff
delete_staff
get_staff_by_email
get_all_staff
remove_staff_from_course
is_staff_assigned_to_course
get_staff_with_courses

Removed Controller
login_staff

### CODE REVIEW

**Review by RynniaRyan — COMMENTED** [review]
**Question: Revaluation of register_staff (Sign-Up)**
I think we discussed that staff are no longer going to have a sign up as this is a closed application. Similar to myElearning as shown below.  Although myElearning should indeed really have a single login page

Only afterwards staff/admin can change their password if they wish to (although its recommended to):

image

**Proposed Changes:** 
**1. Add a way to change password for Staff**

_Is there any other reason you decided to keep it? Let's discuss_ 
@JaleneA

**Comment by JaleneA** [comment]
@RynniaRyan That isn't a "Sign Up" that's for Admin to register a Staff Account to the system, so the Staff can actually have an account to Log In, these are not Controller related concerns, its API Views related.

**Comment by RynniaRyan** [comment]
> @RynniaRyan That isn't a "Sign Up" that's for Admin to register a Staff Account to the system, so the Staff can actually have an account to Log In, these are not Controller related concerns, its API Views related.

**Proposed Changes: Rename register_Staff -> create_Staff**
Ah alrighty, we can you rename the function to create_staff? For simplicity then? We should name it with context to the object itself rather than _'admin using it to do this'_

**Comment by JaleneA** [comment]
@RynniaRyan I don't see how a name change is necessary, both "create_staff" and "register_staff" speaks the same thing.

- An Admin creating a staff and adding them to the system
- An Admin registering a Staff to the system

**Review by stu-dent101 — APPROVED** [review]
The code looks good

**Pull request merged**
