### PR TITLE
Task 06.6 Refactoring : CourseAssessment Controller

### PR DESCRIPTION
**Pull request by JaleneA**
Refactored Controllers
add_course_assessment
get_course_assessment
delete_course_assessment

Removed Controllers
get_CouseAsm_id
get_CourseAsm_code
get_CourseaAsm_level
get_Assessment_type
get_Assessment_id
list_Assessments
get_clashes

Add Controllers
list_course_assessments

### CODE REVIEW

**Review by RynniaRyan — COMMENTED** [review]
In this model is where the controllers to validate a course assessment would be present. 

Similar to how validate_staff and validate_admin where used within [user.py](https://github.com/Fairly-Odd-Functions/Assessment-Scheduler-FOF/blob/main/App/controllers/user.py).

**Comment by JaleneA** [comment]
@RynniaRyan I don't see the logic in validating a course, courses are not users with an email and a password that require validating. There are error handling checks for if the course exist.

```
course = Course.query.get(courseCode)
        if not course:
            return {"Error": "Course with this courseCode does not exist"}
```

**Comment by RynniaRyan** [comment]
> @RynniaRyan I don't see the logic in validating a course, courses are not users with an email and a password that require validating. There are error handling checks for if the course exist.

My bad, I think I gave the wrong example, I meant maybe this is where dynamic functions which hold administrator-defined configurations is to be added  and not within admin.py to validate each an every assessment for a course before is is added.

My idea is that since these configurations are dynamic, they can't be stored within the database (models) so are instead passed through parameters. And so. . .

**Proposed Changes: Add Helper Functions to Validate Scheduled Assessments**
For exmaple, Based on the [Proposed Design Pattern](https://trello.com/c/E1d6q5qj/7-02-proposed-design-pattern):
**1. Add validate_assessment_type_property**
**2. Add validate_assesment_overlap_property**
**3. Add validate_assesment_degree_property**

**Comment by JaleneA** [comment]
@RynniaRyan This controller does not schedule assessments, it simplys links a created assessment to the relevant course

**Comment by JaleneA** [comment]
@RynniaRyan Please elaborate more

**Review by RynniaRyan — APPROVED** [review]
> @RynniaRyan Please elaborate more

Thanks for the in-depth discussion we had earlier.  We shall move these validation controllers to a new controller file 👍 . 

Aside from that clear up, controllers for courseAssesment are fine. Approved 👍

**Pull request merged**
