### PR TITLE
07.2.1. Programme Group Commands Implementation

### PR DESCRIPTION
**Pull request by JaleneA**
Final Installation of my assigned CLI command group :)

### CODE REVIEW

**Comment by JaleneA** [comment]
[07.2.1. Programme Group Commands Implementation](https://trello.com/c/1SfbH0Zb/95-0721-programme-group-commands-implementation)

**Comment by JaleneA** [comment]
[07. CLI Commands Implementation](https://trello.com/c/h6XDC9em/18-07-cli-commands-implementation)

**Comment by stu-dent101** [comment]
For update_programme

I'm unable to run it, I'm receiving errors, when I'm prompted with this "Enter Programme Title: " I tried entering a new programme that was not already in the database and I tried entering one that was already in the database and neither made it work

Screenshot 2024-11-28 112242



I was not able to test the list_programme_courses
Since it does not currently have a command to added courses to a programme, I but ran it and received the expected results '"No Courses Found For Programme:" <Programme Name>'

Overall everything works as intended, except for the update_programme

**Comment by JaleneA** [comment]
> For update_programme
> 
> I'm unable to run it, I'm receiving errors, when I'm prompted with this "Enter Programme Title: " I tried entering a new programme that was not already in the database and I tried entering one that was already in the database and neither made it work
> 
> Screenshot 2024-11-28 112242
> 
> I was not able to test the list_programme_courses Since it does not currently have a command to added courses to a programme, I but ran it and received the expected results '"No Courses Found For Programme:" '
> 
> Overall everything works as intended, except for the update_programme

---

@stu-dent101 
**For list_programme_courses** 
There is commented out code you were supposed to uncomment and initialize the database with 
image
image

---
**For update programme**
In the very same snapshot you sent, you can see that there's simply a typo, programme_tirtle is supposed to be programme_title. As the reviewer you should have looked into this and see if just fixing that would have cured the error, similar for list_programme_courses, when I coded it, I of course tested it somehow, you could have asked what I did or do some improvising to see its functionality.

image
But back to the update_programme fixing that type reveals some more baby errors, but still required attention, you shouldn't have merged this yet, but its alright, I'll note it to fix for later when everything is merged.

**Pull request merged**
