### PR TITLE
07.1.1. Staff Group Commands Implementation

### PR DESCRIPTION
**Pull request by RynniaRyan**
Sorry for the delay, Here are the Staff group commands by me. 🫠

### CODE REVIEW

**Comment by stu-dent101** [comment]
For add-course

I was not able to test it since it does not have a command to add courses just yet, but I did run it and it gave the expected output "{'Error': 'Course Not Found'}" when I tried to assign a staff to a course

The same goes for remove-course it worked as expected for missing the add course command I received "{'Error': 'Course Not Found'}"
The same for get-courses it worked as expected for missing the add course command I received ' "There are Currently No Courses Found For" <firstName lastname>'


Overall the commands execute as intended.

**Review by stu-dent101 — APPROVED** [review]

**Comment by RynniaRyan** [comment]
> For add-course
> 
> I was not able to test it since it does not have a command to add courses just yet, but I did run it and it gave the expected output "{'Error': 'Course Not Found'}" when I tried to assign a staff to a course

What do you mean by there is'nt any commands to add courses? 🤔 
@stu-dent101

**Comment by stu-dent101** [comment]
I does not have a command for me to create a course to add a staff to, yes it has an "add-course" command for me to add staff to, but not one to create a course yet

**Comment by JaleneA** [comment]
[07. CLI Commands Implementation](https://trello.com/c/h6XDC9em/18-07-cli-commands-implementation)

**Pull request merged**
