### PR TITLE
07.CLI Commands Implementation

### PR DESCRIPTION
**Pull request by JaleneA**
_This is the grand branch that contains all CLI Group Commands_

**Status**

- Staff and Course CLI Commands : @RynniaRyan 
- Assessment, Semester, Programme and Admin Commands : @JaleneA

### CODE REVIEW

**Comment by JaleneA** [comment]
Once **_approved_** I'll resolve the conflicts 👍🏽✨ Nothing major @stu-dent101 @DaNJO-Y

**Comment by JaleneA** [comment]
[07.3. CLI Command Fixes](https://trello.com/c/O4dybbFN/126-073-cli-command-fixes)

**Review by stu-dent101 — APPROVED** [review]
Semester command - add_semester works as expected

Course commands work as expected

Staff Commands
add_course works as expected
remove-course works as expected
get-courses works as expected

**Review by DaNJO-Y — APPROVED** [review]

**Comment by JaleneA** [comment]
[09.1. Post-CLI and Post-Tests Cleanup](https://trello.com/c/NA7A4s3c/117-091-post-cli-and-post-tests-cleanup)

**Pull request merged**
